# packages in environment at C:\Users\hansh\anaconda3\envs\DfAnr1:
#
# Name                    Version                   Build  Channel
asgiref                   3.5.0                    pypi_0    pypi
bzip2                     1.0.8                he774522_0  
ca-certificates           2020.10.14                    0    anaconda
certifi                   2020.6.20          pyhd3eb1b0_3  
django                    4.0.3                    pypi_0    pypi
djangorestframework       3.13.1                   pypi_0    pypi
libffi                    3.4.2                h604cdb4_1  
openssl                   1.1.1m               h2bbff1b_0  
pip                       21.2.4          py310haa95532_0  
python                    3.10.0               h96c0403_3  
pytz                      2021.3                   pypi_0    pypi
setuptools                58.0.4          py310haa95532_0  
sqlite                    3.38.0               h2bbff1b_0  
sqlparse                  0.4.2                    pypi_0    pypi
tk                        8.6.11               h2bbff1b_0  
tzdata                    2021.5                   pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wheel                     0.37.1             pyhd3eb1b0_0  
wincertstore              0.2             py310haa95532_2  
xz                        5.2.5                h62dcd97_0  
zlib                      1.2.11               h8cc25b3_4  
